POST http://localhost:3333/livro
Content-Type: application/json

{
    "titulo": "O Senhor dos Anéis",
    "autor": "J.R.R. Tolkien",
    "ano": 1954,
    "lido": false,
    "nota": 9.5
}

###

GET http://localhost:3333/livro

###
put http://localhost:3333/livro/715e605e-39c1-46e9-add8-bb238631dae4
Content-Type: application/json

{
    "titulo": "O Senhor dos Anéis",
    "autor": "J.R.R. Tolkien",
    "ano": 1953,
    "lido": false,
    "nota": 9.5
}

###

DELETE http://localhost:3333/livro/715e605e-39c1-46e9-add8-bb238631dae4